#Defines how often a goat will try to grow its fur, the growth cooldown after shearing, and the chance of it succeeding
#Format: [ticks, cooldown, chance]
"Goat Fur Growth Timings" = [1200, 2400, 0.2]

["Mount Settings"]
	#List of entities that will insulate the player when riding them
	#Format: ["entity-id", insulation-amount]
	#(1 is complete insulation, 0 is no insulation)
	"Insulated Entities" = []

