#Show the config menu button in the Options menu
"Enable In-Game Config" = false
#Overrides all other config options for easy difficulty management
#This value is changed by the in-game config. It does nothing otherwise.
#Range: 1 ~ 5
Difficulty = 2

["Item settings"]
	#Fire Resistance blocks all hot temperatures
	"Fire Resistance Immunity" = true
	#Ice Resistance blocks all cold temperatures
	"Ice Resistance Immunity" = true
	#Thermometer item is required to see world temperature
	"Require Thermometer" = false

["Details about how the player is affected by temperature"]
	#Minimum habitable temperature (default: 0.42857142857142855)
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.30952380952380953
	#Maximum habitable temperature (default: 1.619047619047619)
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.8571428571428572
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 0.75

["Grace Period Details"]
	#Grace period length in ticks (default: 6000)
	#Range: > 0
	"Grace Period Length" = 6000
	#Enables the grace period (default: true)
	"Grace Period Enabled" = true

["Block Effects"]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: falloff>, <*max effect>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#falloff: the block is less effective as distance increases
	#max effect: the max temperature change this block can cause to a player (even with multiple blocks)
	BlockTemps = [["primalwinter:snowy_dirt", -0.1, 2, true, 0.4], ["primalwinter:snowy_coarse_dirt", -0.1, 2, true, 0.4], ["primalwinter:snowy_sand", -0.1, 2, true, 0.4], ["primalwinter:snowy_red_sand", -0.1, 2, true, 0.4], ["primalwinter:snowy_gravel", -0.1, 2, true, 0.4], ["primalwinter:snowy_stone", -0.1, 2, true, 0.4], ["primalwinter:snowy_granite", -0.1, 2, true, 0.4], ["primalwinter:snowy_diorite", -0.1, 2, true, 0.4], ["primalwinter:snowy_andesite", -0.1, 2, true, 0.4], ["#chipped:snow_block", -0.1, 2, true, 0.4], ["molten_geodes:molten_ochrum", 1.0, 4, true, 4.0], ["molten_geodes:molten_crimsite", 1.0, 4, true, 4.0], ["molten_geodes:molten_asurine", 1.0, 4, true, 4.0], ["molten_geodes:molten_veridium", 1, 4, true, 4.0], ["minecraft:campfire", 0.3, 7, true, 1.2], ["minecraft:soul_campfire", -0.3, 7, true, 1.2], ["minecraft:soul_fire", -0.2, 7, true, 0.8], ["minecraft:fire", 0.2, 7, true, 0.8], ["#chipped:magma_block", 0.2, 3, true, 0.8], ["#chipped:ice", -0.1, 4, true, 0.5], ["#chipped:packed_ice", -0.2, 4, true, 1.0], ["#chipped:blue_ice", -0.3, 4, true, 1.0]]

["Hearth Strength"]
	#How strong the hearth is (default: 0.5)
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5

["Cold Soul Fire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

["Misc temperature-related things"]
	#Sets whether damage scales with difficulty
	"Damage Scaling" = true
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Prevent Sleep When in Danger" = true

